language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
install: true
script: "./shared/gradlew clean build install && ./order/gradlew clean build && ./catalog/gradlew clean build && ./delivery/gradlew clean build && ./bakery/gradlew clean build"
after_success: "./publish.sh"
env:
  global:
  - CI_NAME=travis-ci
