order:
  build: order
  volumes:
    - order/build/libs:/app
  external_links:
    - infrastructure_rabbitmq_1:rabbitmq
  environment:
    - PROFILE=prod
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PORT=5672
    - PORT=8081
  ports:
   - "8081:8081"

catalog:
  build: catalog
  volumes:
    - catalog/build/libs:/app
  external_links:
    - infrastructure_rabbitmq_1:rabbitmq
  environment:
    - PROFILE=prod
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PORT=5672
    - PORT=8082
  ports:
   - "8082:8082"
