microservice:
  build: .
  volumes:
    - build/libs:/app
  external_links:
    - eventbus_rabbitmq_1:rabbitmq
  environment:
    - PROFILE=prod
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PORT=5672
    - PORT=8080
  ports:
   - "8080:8080"
