# ==============================================================================
data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/rabbitmq
# ==============================================================================
rabbitmq:
  image: rabbitmq:management
  volumes_from:
    - data
  ports:
    - "5672:5672"
    - "15672:15672"
# ==============================================================================
configserver:
  image: epizza/config-server
  # mount /repo as volume from docker-compose.override.yml
  ports:
    - "8888:8888"
  environment:
    - _JAVA_OPTIONS=-Xmx256m
    - SPRING_PROFILES_ACTIVE=native
    - SPRING_CLOUD_CONFIG_SERVER_BOOTSTRAP=true
    - SPRING_CLOUD_CONFIG_LABEL=master
    - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:///repo
    - DOCKER_IP=${DOCKER_IP}
# ==============================================================================
order:
  image: epizza/order
  links:
    - rabbitmq
    - configserver
  ports:
    - "8082:8082"
  environment:
    - _JAVA_OPTIONS=-Xmx256m
    - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
    - SPRING_CLOUD_CONFIG_LABEL=dev
# ==============================================================================
bakery:
  image: epizza/bakery
  links:
    - rabbitmq
    - configserver
  ports:
    - "8083:8083"
  environment:
    - _JAVA_OPTIONS=-Xmx256m
    - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
    - SPRING_CLOUD_CONFIG_LABEL=dev
# ==============================================================================
#delivery:
#  image: epizza/delivery
#  links:
#    - rabbitmq
#    - configserver
#  ports:
#    - "8084:8084"
#  environment:
#    - _JAVA_OPTIONS=-Xmx256m
# ==============================================================================
orderui:
  image: epizza/order-ui
  ports:
    - "8085:8085"
  environment:
    - _JAVA_OPTIONS=-Xmx256m
    - API_HOST=http://${DOCKER_IP}:8082
