spring:
  application:
    name: order
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}

server:
  port: ${port:8082}

logging:
  level:
    com.epages: INFO
    feign: DEBUG
    org.springframework: INFO
