server:
  port: ${port:8082}

logging:
  level:
    com.epages: INFO
    org.springframework: INFO
    org.springframework.amqp.rabbit: OFF

spring:
  jmx:
    enabled: false

#  jpa:
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
