spring:
  application:
    name: delivery
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}
  output:
    ansi:
      enabled: ALWAYS

server:
  port: ${port:8084}

logging:
  level:
    com.epages: INFO
    feign: DEBUG
    org.springframework: INFO
