spring:
  application:
    name: delivery
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}

server:
  port: ${port:8084}

logging:
  level:
    com.epages: INFO
    feign: DEBUG
    org.springframework: INFO
#    http.wire: DEBUG

orders:
  baseUri: "http://localhost:8082/"