spring:
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework.amqp: 'OFF'
