spring:
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}

  jpa:
    generate-ddl: true

  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO

management:
  context-path: /system
