spring:
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}

  jpa:
    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true

  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
